
/* Drop Indexes */

DROP INDEX UQ_INV_MGT_DIST_LOCATION_1;
DROP INDEX UQ_INV_MGT_SALES_ORDER_1;
DROP INDEX UQ_INV_MGT_STATION_1;
DROP INDEX UQ_INV_MGT_TYPE_1;
DROP INDEX UQ_INV_MGT_USER_ROLE_1;



/* Drop Tables */

DROP TABLE INV_MGT_CUSTOMER;
DROP TABLE INV_MGT_DELIVERY_PLAN;
DROP TABLE INV_MGT_DELIVERY_REALISATION;
DROP TABLE INV_MGT_DEPOT;
DROP TABLE INV_MGT_DIST_LOCATION;
DROP TABLE INV_MGT_MARGIN;
DROP TABLE INV_MGT_OUTPUT;
DROP TABLE INV_MGT_PRICE;
DROP TABLE INV_MGT_REAL_STOCK;
DROP TABLE INV_MGT_SALES_ORDER;
DROP TABLE INV_MGT_STATION;
DROP TABLE INV_MGT_SUPPLY;
DROP TABLE INV_MGT_TANK_CAPACITY;
DROP TABLE INV_MGT_TYPE;
DROP TABLE INV_MGT_USER_ROLE;
DROP TABLE OVERHEAD_COST;
DROP TABLE WORK_IN_CAPITAL;




/* Create Tables */

CREATE TABLE INV_MGT_CUSTOMER
(
	ID INT NOT NULL,
	CUSTOMER_TYPE VARCHAR(50) NOT NULL,
	CUSTOMER_DESC VARCHAR(50),
	CATEGORY VARCHAR(10),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_DELIVERY_PLAN
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	QUANTITY DECIMAL(50,2) NOT NULL,
	DELIVERY_DATE DATE NOT NULL,
	DELIVERY_SHIFT_NUMBER VARCHAR(10) NOT NULL,
	SALES_ORDER_NUMBER VARCHAR(50) NOT NULL,
	STATION_ID VARCHAR(50) NOT NULL,
	DELIVERY_MESSAGE VARCHAR(255),
	PLAN_STATUS VARCHAR(10),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_DELIVERY_REALISATION
(
	ID INT NOT NULL,
	SALES_ORDER_NUMBER VARCHAR(50) NOT NULL,
	STATION_ID VARCHAR(50) NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	QUANTITY DECIMAL(50,2) NOT NULL,
	PLATE_NUMBER VARCHAR(20) NOT NULL,
	DRIVER_NAME VARCHAR(50) NOT NULL,
	DELIVERY_DATE DATE NOT NULL,
	DELIVERY_TIME VARCHAR(20) NOT NULL,
	DELIVERY_SHIFT_NUMBER VARCHAR(10) NOT NULL,
	DELIVERY_MESSAGE VARCHAR(255),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_DEPOT
(
	ID INT NOT NULL,
	DEPOT_CODE VARCHAR(50) NOT NULL,
	DEPOT_NAME VARCHAR(50) NOT NULL,
	DEPOT_ADDRESS VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_DIST_LOCATION
(
	ID INT NOT NULL,
	LOCATION_CODE VARCHAR(50) NOT NULL UNIQUE,
	LOCATION_NAME VARCHAR(50),
	SUPPLY_POINT VARCHAR(50) NOT NULL,
	SALES_AREA_MANAGER VARCHAR(50) NOT NULL,
	DEPOT_CODE VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_MARGIN
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	MARGIN_VALUE DECIMAL(10,2) NOT NULL,
	STATION_ID VARCHAR(50),
	START_DATE DATETIME,
	END_DATE DATETIME,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_OUTPUT
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	CUSTOMER_TYPE VARCHAR(50) NOT NULL,
	OUTPUT_VALUE DECIMAL(50,2) NOT NULL,
	OUTPUT_DATE DATE NOT NULL,
	UNIT_PRICE DECIMAL(50,2) NOT NULL,
	BEGIN_STAND_METER DECIMAL(50,2) DEFAULT 0.00,
	END_STAND_METER DECIMAL(50,2) DEFAULT 0.00,
	VEHICLE_TYPE VARCHAR(50),
	TERA_VALUE DECIMAL(10,2),
	PUMP_ID VARCHAR(10),
	NOSEL_ID VARCHAR(10),
	OUTPUT_TIME VARCHAR(20),
	CATEGORY VARCHAR(10),
	STATION_ID VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_PRICE
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	UNIT_PRICE DECIMAL(10,2) NOT NULL,
	CATEGORY VARCHAR(10),
	STATION_ID VARCHAR(50),
	START_DATE DATETIME,
	END_DATE DATETIME,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_REAL_STOCK
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NOT NULL,
	QUANTITY DECIMAL(50,2) NOT NULL,
	STATION_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_SALES_ORDER
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	QUANTITY DECIMAL(50,0) NOT NULL,
	BANK_TRANSFER_DATE DATETIME NOT NULL,
	DELIVERY_DATE DATE NOT NULL,
	DELIVERY_SHIFT_NUMBER VARCHAR(10) NOT NULL,
	BANK_NAME VARCHAR(50) NOT NULL,
	BANK_ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
	SALES_ORDER_NUMBER VARCHAR(50) NOT NULL,
	STATION_ID VARCHAR(50) NOT NULL,
	ORDER_MESSAGE VARCHAR(255),
	ORDER_STATUS VARCHAR(10),
	ORDER_DATE DATETIME,
	RECEIVE_DATE DATETIME,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_STATION
(
	ID INT NOT NULL,
	STATION_ID VARCHAR(50) NOT NULL UNIQUE,
	STATION_ADDRESS VARCHAR(50),
	LOCATION_CODE VARCHAR(50) NOT NULL,
	SUPPLY_POINT_DISTANCE DECIMAL(50,2),
	MAX_TOLERANCE DECIMAL(50,2),
	STATION_STATUS VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_SUPPLY
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	SUPPLY_VALUE DECIMAL(50,2) NOT NULL,
	SUPPLY_DATE DATE NOT NULL,
	DELIVERY_ORDER_NUMBER VARCHAR(20) NOT NULL,
	PLATE_NUMBER VARCHAR(20),
	NIAP_NUMBER VARCHAR(20),
	STATION_ID VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_TANK_CAPACITY
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL,
	TANK_CAPACITY DECIMAL(50,2) NOT NULL,
	STATION_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_TYPE
(
	ID INT NOT NULL,
	INV_TYPE VARCHAR(50) NOT NULL UNIQUE,
	INV_DESC VARCHAR(50),
	PRODUCT_TYPE VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE INV_MGT_USER_ROLE
(
	ID INT NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	USER_ROLE VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	STATION_ID VARCHAR(50),
	EMAIL_ADDRESS VARCHAR(50),
	ACCOUNT_ACTIVATED VARCHAR(3),
	PRIMARY KEY (ID)
);


CREATE TABLE OVERHEAD_COST
(
	ID INT NOT NULL,
	OVH_CODE VARCHAR(20) NOT NULL,
	OVH_DESC VARCHAR(50) NOT NULL,
	OVH_VALUE DECIMAL(50,2) NOT NULL,
	OVH_DATE DATE NOT NULL,
	STATION_ID VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE WORK_IN_CAPITAL
(
	ID INT NOT NULL,
	C_VALUE DECIMAL(50,2) NOT NULL,
	C_DESC VARCHAR(10),
	C_CODE VARCHAR(10) NOT NULL,
	STATION_ID VARCHAR(50),
	PRIMARY KEY (ID)
);



/* Create Indexes */

CREATE UNIQUE INDEX UQ_INV_MGT_DIST_LOCATION_1 ON INV_MGT_DIST_LOCATION USING BTREE (LOCATION_CODE ASC);
CREATE UNIQUE INDEX UQ_INV_MGT_SALES_ORDER_1 ON INV_MGT_SALES_ORDER USING BTREE (SALES_ORDER_NUMBER ASC, STATION_ID ASC);
CREATE UNIQUE INDEX UQ_INV_MGT_STATION_1 ON INV_MGT_STATION USING BTREE (STATION_ID ASC);
CREATE UNIQUE INDEX UQ_INV_MGT_TYPE_1 ON INV_MGT_TYPE USING BTREE (INV_TYPE ASC);
CREATE UNIQUE INDEX UQ_INV_MGT_USER_ROLE_1 ON INV_MGT_USER_ROLE USING BTREE (USER_NAME ASC);



